server:
  port: 0

springdoc:
  paths-to-exclude: /exchange/send,/agents/hubControl

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: SonicQuartz
            instanceId: AUTO
          jobStore:
            isClustered: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

robot:
  client:
    host: http://${SONIC_SERVER_HOST:localhost}:${SONIC_SERVER_PORT:3000}
  img:
    success: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/suc.png"
    warning: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/warn.png"
    error: "https://gitee.com/sonic-cloud/sonic-cloud/raw/main/src/assets/fail.png"

sonic:
  websocket:
    retry:
      max-attempts: 10        # 最大重试次数，默认10次
      base-delay: 1          # 基础延迟时间(秒)，默认1秒
      max-delay: 30          # 最大延迟时间(秒)，默认30秒
