spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  jdbc:mysql://{mysql host}:{mysql port}/{database}
    url: jdbc:mysql://${MYSQL_HOST:172.16.37.180}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic_dev}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
#    url: jdbc:mysql://${MYSQL_HOST:172.16.37.180}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    # mysql username
    username: ${MYSQL_USERNAME:root}
    # mysql password
    password: ${MYSQL_PASSWORD:123456}
#    schema:
#      - classpath:data.sql
#  sql:
#    init:
#      mode: always

mybatis-plus:
  mapper-locations:  classpath*:mapping/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
#  mapper-locations: classpath:mapper/*.xml
  global-config:
    banner: false
  configuration:
    cache-enabled: false
    localCacheScope: STATEMENT
    # sql log
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

actable:
  model:
    pack: org.cloud.sonic.controller.models.domain
  table:
    auto: update
  database:
    type: mysql